trigger:
- master

pool:
  name: classicagent

steps:

- task: AzureCLI@2
  displayName: Show Subscription
  inputs:
    azureSubscription: 'azure-svc'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      Write-Host "===== CURRENT AZURE ACCOUNT ====="
      az account show

- powershell: |
    terraform init
  displayName: Terraform Init

- powershell: |
    terraform validate
  displayName: Terraform Validate

- powershell: |
    terraform plan -out=tfplan
  displayName: Terraform Plan

- powershell: |
    terraform apply -auto-approve tfplan
  displayName: Terraform Apply